# Port for the API Gateway
server:
  port: 8079

# Unique application name for Eureka registration
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Enable discovering services from Eureka
      discovery:
        locator:
          enabled: true
      # Define the routes
      routes:
        - id: product-service-route
          uri: lb://product-service     
          predicates:
            - Path=/api/products/**
        - id: inventory-service-route
          uri: lb://inventory-service  
          predicates:
            - Path=/api/inventory/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/